
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/activiti-workflow?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Abc@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    ##  Hikari 连接池配置
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 10
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名称，默认HikariPool-1
      pool-name: Workflow-HikariPool
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 60000
      connection-test-query: SELECT 1

  activiti:
    # 自动生成Activity相关表，表创建后设置成false
    database-schema-update: true
    # 开启历史表的使用，否则将不会创建8张历史表
    db-history-used: true
    # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full
    # 是否自动部署，自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    # 在流程引擎启动就激活AsyncExecutor,异步：true-开启（默认）、false-关闭
    async-executor-activate: true
    # 流程定义文件路径
    process-definition-location-prefix: classpath:/processes/
server:
  port: 80