server:
  port: 8080
spring:
  application:
    name: springboot-rabbitmq

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /alwyn
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
